# Generated by Django 5.0.3 on 2024-04-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-Contact']},
        ),
        migrations.AddField(
            model_name='student',
            name='City',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
