# Generated by Django 5.0.3 on 2024-04-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_options_student_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='stu_table',
        ),
    ]
